### PR TITLE
 Updated Home Page UI #134 

### PR DESCRIPTION
**Pull request by JdevStudios**
The image of the UI was super blurry and I couldn't make out the content of the card above the video iframe.

### CODE REVIEW

**Comment by TurqPBC** [comment]
I made a couple of comments in the figma regarding the banner text and button. Would you please refer to the figma on those?

The section with the 1, 2, 3, 4 seems to be missing.

The video has a boarder around it that isn't in the figma. 

The Active Issues v Past Issues does match the figma.

The cards don't include the funding goal, the corners aren't rounded, it has an extra "Share" button as well as the "Tweet" button (please include only one, but maintain the current Tweet functionality), there are undesired grey bars on the top and bottom of the cards, the divider between "Issue Details" and the "Share" button is a vertical line ("|") rather than the figma arrow line (">"), and the text is not left justified as it is in the figma.

The footer does not match the figma.

Would you please also ensure that it is mobile responsive with components centered on mobile?

**Comment by TurqPBC** [comment]
> The image of the UI was super blurry and I couldn't make out the content of the card above the video iframe.

turqUXscreen1

**Comment by JdevStudios** [comment]
> I made a couple of comments in the figma regarding the banner text and button. Would you please refer to the figma on those?
> 
> The section with the 1, 2, 3, 4 seems to be missing.
> 
> The video has a boarder around it that isn't in the figma.
> 
> The Active Issues v Past Issues does match the figma.
> 
> The cards don't include the funding goal, the corners aren't rounded, it has an extra "Share" button as well as the "Tweet" button (please include only one, but maintain the current Tweet functionality), there are undesired grey bars on the top and bottom of the cards, the divider between "Issue Details" and the "Share" button is a vertical line ("|") rather than the figma arrow line (">"), and the text is not left justified as it is in the figma.
> 
> The footer does not match the figma.
> 
> Would you please also ensure that it is mobile responsive with components centered on mobile?

I will make the changes you suggested in my next PR. The figma I exported was low resolution for some reason so I couldn't recreate it, but now you sent me the full res image I'll improve on my UI redesign. Thank you!

**Comment by TurqPBC** [comment]
> > I made a couple of comments in the figma regarding the banner text and button. Would you please refer to the figma on those?
> > The section with the 1, 2, 3, 4 seems to be missing.
> > The video has a boarder around it that isn't in the figma.
> > The Active Issues v Past Issues does match the figma.
> > The cards don't include the funding goal, the corners aren't rounded, it has an extra "Share" button as well as the "Tweet" button (please include only one, but maintain the current Tweet functionality), there are undesired grey bars on the top and bottom of the cards, the divider between "Issue Details" and the "Share" button is a vertical line ("|") rather than the figma arrow line (">"), and the text is not left justified as it is in the figma.
> > The footer does not match the figma.
> > Would you please also ensure that it is mobile responsive with components centered on mobile?
> 
> I will make the changes you suggested in my next PR. The figma I exported was low resolution for some reason so I couldn't recreate it, but now you sent me the full res image I'll improve on my UI redesign. Thank you!

Rather than a separate PR, would you be able to make an update to this PR?

**Comment by JdevStudios** [comment]
> > > I made a couple of comments in the figma regarding the banner text and button. Would you please refer to the figma on those?
> > > The section with the 1, 2, 3, 4 seems to be missing.
> > > The video has a boarder around it that isn't in the figma.
> > > The Active Issues v Past Issues does match the figma.
> > > The cards don't include the funding goal, the corners aren't rounded, it has an extra "Share" button as well as the "Tweet" button (please include only one, but maintain the current Tweet functionality), there are undesired grey bars on the top and bottom of the cards, the divider between "Issue Details" and the "Share" button is a vertical line ("|") rather than the figma arrow line (">"), and the text is not left justified as it is in the figma.
> > > The footer does not match the figma.
> > > Would you please also ensure that it is mobile responsive with components centered on mobile?
> > 
> > 
> > I will make the changes you suggested in my next PR. The figma I exported was low resolution for some reason so I couldn't recreate it, but now you sent me the full res image I'll improve on my UI redesign. Thank you!
> 
> Rather than a separate PR, would you be able to make an update to this PR?

Sure thing.

**Review by JdevStudios — COMMENTED** [review]
Updates

**Comment by TurqPBC** [comment]
Hey, this looks really good. Can we make 4 small changed before merging the PR and getting you paid?

1. Center Hero Banner content, including the "Raise and Issue" button
2. Capitalize "you can also become a drafter..."
3. Add a bit more space between "you can also become a drafter..." and the 1, 2, 3, 4 area
4. Default list of issues to "Active Issues" rather than Past Issues as you have it

After that I think we're good

**Comment by TurqPBC** [comment]
Sorry, I also just saw that the mobile responsiveness isn't working right. Please add that to my above list of 4.

**Comment by JdevStudios** [comment]
> Sorry, I also just saw that the mobile responsiveness isn't working right. Please add that to my above list of 4.

Hi, on which elements?

**Comment by JdevStudios** [comment]
> Hey, this looks really good. Can we make 4 small changed before merging the PR and getting you paid?
> 
>     1. Center Hero Banner content, including the "Raise and Issue" button
> 
>     2. Capitalize "you can also become a drafter..."
> 
>     3. Add a bit more space between "you can also become a drafter..." and the 1, 2, 3, 4 area
> 
>     4. Default list of issues to "Active Issues" rather than Past Issues as you have it
> 
> 
> After that I think we're good

Thanks, I'll make the changes.

**Comment by TurqPBC** [comment]
> > Sorry, I also just saw that the mobile responsiveness isn't working right. Please add that to my above list of 4.
> 
> 
> 
> Hi, on which elements?

In the 1, 2, 3, 4 section and on the video.

**Comment by JdevStudios** [comment]
Disregard the last commit, thanks.

**Comment by TurqPBC** [comment]
It's closer, but the responsiveness is still odd.

image

**Comment by TurqPBC** [comment]
I saw that you made a couple more commits but I'm not seeing a difference on the responsiveness.

**Comment by TurqPBC** [comment]
I would think to get the mobile responsive right on the 1,2, 3, 4 elements you would want to slot them on top of each other from top to bottom 1, 2, 3, 4. 

Also with the card overflowing on moble view made padding would help? Not sure, I'm not a front-end guy.

**Comment by JdevStudios** [comment]
A new user left a comment. This user must be approved by a Netlify team owner before comments can be displayed.

[Approve this user](https://app.netlify.com/teams/turqpbc/reviewers)

**Comment by JdevStudios** [comment]
### Responsiveness has been  fixed

**Pull request merged**
