### PR TITLE
User/Admin user can edit post

### LINKED ISSUE #102: Enable users (and Admins) to edit Issues they posted

### PR DESCRIPTION
**Pull request by mushroomgenie**
Fixes #102

### CODE REVIEW

**Comment by TurqPBC** [comment]
Can the edit button component be enlarged?
turqEditPage

Can the edit fields be stacked vertically?
turqUpdatePage

Can a location update be included?

**Comment by mushroomgenie** [comment]
@TurqPBC I have these changes locally I will push them right now and can you please check then ?

**Comment by mushroomgenie** [comment]
@TurqPBC Did you see the latest ?

**Comment by TurqPBC** [comment]
The edit page is now appearing blank for me..

**Comment by mushroomgenie** [comment]
@TurqPBC That happens on few issues not all issues. Can you reconfirm? Few issues apparently don't have an id, so they throw an error. I have faced this issue while developing as well.

**Comment by TurqPBC** [comment]
Gotcha. I'll look on a different issue. One moment.

**Comment by TurqPBC** [comment]
I signed in with a non-admin account and posted a new issue but it was still showing blank when I went to edit it.

**Comment by mushroomgenie** [comment]
Okay I will look into this.

**Comment by mushroomgenie** [comment]
@TurqPBC It's working fine for me in fact I was also able to edit the contest from a non-admin account. Can you try clearing your cache ?

**Comment by TurqPBC** [comment]
Okay. One moment.

**Comment by TurqPBC** [comment]
Okay, they are looking stacked now. The problem I'm seeing now is that data from the "Legislation Needed" step is being populated in the location field. 

There no data is being populated in the Legislation Needed edit field, and the wrong information is being populated in the Location dit field.

image

**Comment by mushroomgenie** [comment]
@TurqPBC Should be fixed now

**Comment by TurqPBC** [comment]
Looking good!

**Comment by mushroomgenie** [comment]
@TurqPBC Can we merge it ?

**Comment by TurqPBC** [comment]
Can you add just a little padding on the side of the mobile view and we'll get this one closed out?

image

**Comment by TurqPBC** [comment]
> @TurqPBC Can we merge it ?

I added another comment. Can you add a little space on the sides on mobile responsive view and then I'll merge?

**Comment by mushroomgenie** [comment]
@TurqPBC I added padding.

**Pull request merged**
