### PR TITLE
Update Issue posting

### LINKED ISSUE #127: Update Issue Posting Flow
- **Move home button on first page of issue posting flow**
Move the home button to the first page of the issue posting flow. See Figma below
[FIGMA >>>>](https://www.figma.com/file/VXURTynWVuaHDj9BzgnsYV/moveHomeButtonCRO?node-id=0%3A1)

- **Make flow tabs clickable after having moved through tab**
image
A user should be able to return to tabs that they have already completed by clicking on the corresponding tab
A user should not be able to click on tabs which they have not yet completed

- **Save user's content if they leave and come back to issue posting**
When the user leaves the page and later returns (login,refresh,etc) the user's content should be saved and appear in the appropriate fields
When a user logs out the content does not need to be saved
**Technical Note:** You will probably want to store this in the browser's local storage so it persists page refreshes
- **Move log in gate to the end of the flow**
The user should prompted to login after they complete the location tab and before they enter the funding tab
The user should no longer be required to log in before landing on the issue posting page
- **Redirect user back to issue posting flow after logging in**
When a user is redirected to the login flow, after logging in they should be redirected back to the issue posting flow
**Technical Note:** this logic is already implemented in the `/pages/login.js` component. You will just need to make sure the referrer is set

NOTES:

    Please fork from the TurqV2 repo, CROTest branch and then submit a PR to our CROTest branch for review
    Please make sure the page responsively resizes on mobile

### PR DESCRIPTION
**Pull request by mushroomgenie**
Fixes #127

### CODE REVIEW

**Comment by TurqPBC** [comment]
- Looks like the login gate was not moved toward the end of the issue posting workflow
- It doesn't look like the step titles of the flow are clickable to return to that step after the user has proceeded through that step
- I'm not sure if the content added to the steps is retained post-login as the login is still in front of the issue posting rather than toward the end

**Comment by mushroomgenie** [comment]
@TurqPBC I'll make these changes.

**Comment by TurqPBC** [comment]
The sign-in gate is at the end, which is right, and after signing in the user is brought back to the posting flow, which is right, BUT it wipes all of the content the user put in prior to signing in. This is a problem.

**Comment by TurqPBC** [comment]
Okay, the content is now persisting, which is awesome. But there's a bug after I post and then when I go back to the home page and select "View All Issues". It's showing me the issue page that I just made rather than showing me all the issues.

**Pull request merged**
